#!/usr/bin/env bash
# This script pings an IP address passed as an argument 5 times

# Checks if an argument is passed
if [ -z "$1" ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
fi

# Pings if IP Address is passed
ping -c 5 "$1"
