#!/usr/bin/env bash
# Bash  script that displays the list of running processes
# Shows all procesess for all users including those which might not have a TTY
# Display in a user-oriented format. Show process hierarchy

ps -a -x -u -f
