#!/usr/bin/env bash
# Script that dislays 'To infinity and beyond' indefinitely with a 'sleep 2' in between each iteration

# Trap SIGTERM signal and print a message
trap "echo 'I am invincible!!!'" SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
